#theme: jekyll-theme-midnight
#remote_theme: chrisrhymes/bulma-clean-theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
fixed_navbar: top
paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-include-cache